version: "3.5"
services:
  scraper_web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      BACKEND_ADDRESS: "http://localhost:8080/graphql"